### PR TITLE
Preparing platformIO configuration as build system

### PR DESCRIPTION
**Pull request by matthiasdanner**
platformIO can be used as build system with this config

### CODE REVIEW

**Comment by oderwat** [comment]
I have to confess that I don't know what this means. Could you describe what this means exactly?

**Comment by matthiasdanner** [comment]
platformIO is another build system like the arduino IDE. I use it to build SkyNet from the commandline on my attached raspberrypi and upload it to the printer. The platformio.ini is like the boards.txt from the arduino ide

**Comment by oderwat** [comment]
OK found it ... http://platformio.org/ installing right now.

**Comment by oderwat** [comment]
Nice .. works like a charm for me. Thank you for the headups on this!

I just needed to install platformio with homebrew and could use it directly:

This for reference (OS X), which is grabbing the newest devel even if it was force pushed:

```
brew install platformio
```

Here a small script I created quickly for building the latest SkyNet3D from GitHub:

```
cd <your skynet github installation>
# backup our config
cp Marlin/Configuration.h /tmp
cp Marlin/Configuration_adv.h /tmp
# update from Github
git fetch
git checkout SkyNet3D-Devel # or the branch you use
git reset origin/`git rev-parse --abbrev-ref HEAD` --hard
# restore the config
cp /tmp/Configuration.h Marlin/
cp /tmp/Configuration_adv.h Marlin/
# build and upload the new skynet
platformio run -d Marlin -t upload 
```

**Comment by matthiasdanner** [comment]
Nice to hear it works for you. :D

I tried to get the Makefile running, which I think would be the cleaner solution, but I'm getting compile time errors. I think I'm still having some misconfigurations in there.
Also a guy in the Marlin repository pointed out that platformio was more stable for him (https://github.com/MarlinFirmware/Marlin/issues/5015#issuecomment-255533405), so I just went with it.

Awesome, thanks for the script. Just tried it, I only had to set the alias for git co.

**Comment by oderwat** [comment]
Cool. I forgot about the alias usage. I replaced it with checkout in the "instructions".

**Pull request merged**
