### PR TITLE
Change Z_SAFE_HOMING to put the nozzle in the middle of the sensor probe area for ABL

### PR DESCRIPTION
**Pull request by benlye**

### CODE REVIEW

**Comment by oderwat** [comment]
You have a very valid point there and I think this may explain some of the problems people have. Which mostly would not affect me, because I always level the bed manually before measuring Z-offset.

Nevertheless, if one would not like to have the sensor in the middle of the bed, this should be corrected where the probe offsets get applied with G28 instead of redefining the home point in a way that it "resolves" to the real center.

Either way you probe at another location as the nozzle is. I think the probe in the middle is the correct way.

But one should better G28 with the probe in the middle and then move the nose into the middle to adjust the Z offset. This is easily be done by G28 ... G1 X110 Y110 ... adjust your Z offset.. G30 X110 Y110 retest probe..

**Comment by benlye** [comment]
> But one should better G28 with the probe in the middle and then move the nose into the middle to adjust the Z offset. This is easily be done by G28 ... G1 X110 Y110 ... adjust your Z offset.. G30 X110 Y110 retest probe..

No, I think that that will make it worse.  The point is that in ABL the mesh is centred around the home point.  If you set your Z-offset somewhere other than home you are guaranteeing that it will be out because the grid will apply Z=0 somewhere other than where you set/measured it to be.

Humour me, try it my way.  I will also test both and provide the outcomes.

**Comment by oderwat** [comment]
If you measure with the nozzle in the middle isn't it that home point?

**Comment by benlye** [comment]
> If you measure with the nozzle in the middle isn't it that home point?

I don't think that the point where you set the offset is stored in the EEPROM, is it?

**Comment by oderwat** [comment]
Not the X and Y coordinates. My point is: The Z offset is supposed to be the difference between the tip of the nozzle and the trigger point of the sensor. If you do not measure the triggering point at the same position where your nozzle is touching the bed you introduce an error. Just think of putting a coin at the position of the nozzle but not where the sensor is. Measuring will not reflect the distance between the nozzle tip and the triggering point because the triggering point is now lower. I think the same may  happen if the bed is tilted to much. You don't really get the Z-offset but also the difference of the tilt in between those points.

**Comment by benlye** [comment]
OK, I see where you are coming from.  That's why my code for Z_SAFE_HOME puts the nozzle at the centre point where the sensor probes (or within 1-2mm of it, depending on integer rounding).  I do G28 to home before I set my Z-offset, then when G29 runs, it probes the very spot where I calibrated my offset.  This works for odd numbers of probe points because the middle always gets probed.

With the original SN3D Z_SAFE_HOME you are relying on the user to think about where they put the nozzle for the calibration, and I bet most do not.

I need to test this more tomorrow.  I managed to soft-brick my printer earlier and only just recovered it :-)

**Comment by oderwat** [comment]
I am pretty sure that G29 has nothing to do with how you measure the Z offset nor with centering the nozzle. It just calculates the values from probing and in addition applies the z-offset. the z-offset itself is "dumb" and constant. you can actually make the z-offset 0 and level the bed "in the air" on a tilted extra surface. if you then move the nozzle with G1 you see how the z axis moves to adjust to the tilt. The rotation matrix is positioned in the center of the coordinate system. This is why I think it is important to have the bed size correctly but nothing else is really affecting it. not even the sensor position. It is just important that the system knows where on the real plane the sensor is located. hence the offset definition. which means if you have a wrong offset, the center of the matrix will be wrong.

**Comment by benlye** [comment]
I found what got me thinking this way: https://github.com/MarlinFirmware/Marlin/pull/4710

- _The current position after probing is correct for XY but Z is only known to the steppers_
- _The leveling matrix was always being applied based on your distance from (0, 0, 0) but there's no guarantee that Z at (0, 0) is actually 0. In fact, Z is only "known" to be "accurate" at the home position, which may theoretically be anywhere, especially when using Z_SAFE_HOMING._

_This PR uses the actual home position as the pivot point for the matrix instead of always 0, 0._

The G28 point matters, because that's where we hit the Z stop - "where we know Z to be accurate".

What do you think?

**Comment by benlye** [comment]
Imagine that you have a bed that is neither perfectly flat nor perfectly level.  Assume that your nozzle is 2mm below your sensor trigger height.  

You run G28, and the probe acts as the Z-endstop to tell the printer where Z=0 is.  You can set your nozzle offset here with high certainty because it is mechanically accurate - you drive the nozzle down 2mm and it is touching the bed.

However, if your move your nozzle to another point on the bed, because the bed is not level or flat, when you drive the nozzle down to the bed your Z-offset will be different, because the bed can be nearer to or further away from the absolute Z-axis point where we hit the endstop - imagine you measure -2.1 because this point in the bed is 0.1mm lower than the G28 point.  If you set -2.1 as your Z-offset you are not going to have good luck printing because the printer will expect an offset of -2.1 at the point where the Z-endstop occurs - i.e. at the G28 XY coordinates.

The only way to compensate for that is to do G28, G29, then set your Z-offset with a value that has been auto-compensated by ABL.  But that assumes that ABL is accurate, which I think we know is not always the case (yet).

So perhaps the exact position of Z_SAFE_HOMING does not matter as much for ABL - the fulcrum of plane will be moved to compensate, but I still think that having the home point nearer to the centre would be better than where it is by default currently, which is [110,110] plus or minus the sensor offset.

What you definitely don't want people doing is G28, moving the nozzle, then measuring and storing the nozzle offset.

**Comment by oderwat** [comment]
> What you definitely don't want people doing is G28, moving the nozzle, then measuring and storing the nozzle offset.

That is exactly what I want :) because that way they measure the real offset between triggerpoint and the nozzle

**Comment by benlye** [comment]
> That is exactly what I want :) because that way they measure the real offset between triggerpoint and the nozzle

OK, yes, you have to move it in the Z-axis, but not X or Y!

**Comment by oderwat** [comment]
Measuring the bed with ABL has nothing to do with the offset of the sensor to the nozzle besides that the hardware moves the sensor to the xy coordinates which would correspont to a nozzle position to measure a the position the nozzle will be when printing.

The Z offset is **never** different! You don't seem to understand how it works! The Z-Offset is (again) the distance between nozzle and sensor! It is constant everywhere besides of slight tilting of the head which gives slightly different results for the distance even on a flat bed if the x axis is tilt because the z-rods are not even. which is another thing that needs to be correct for everything to work.

**Comment by oderwat** [comment]
G28 moves to the sensor to the middle check the "nozzle x and y" by M114 ... you then move the nozzle to the middle G0 X110 Y110 .. then you make it go down to the bed. G92 Z0 to set z=0 there. Then you move the nozzle up.. then you move the sensor back to the middle by G0 Xnotedx Ynotedy ... so now you have Z 0 at the exact point below the sensor and then you move the sensor down till it triggers. This way you measure the real distance between the sensor and the nozzle.

**Comment by benlye** [comment]
> G28 moves to the sensor to the middle check the "nozzle x and y" by M114 ... you then move the nozzle to the middle G0 X110 Y110 .. then you make it go down to the bed. G92 Z0 to set z=0 there. Then you move the nozzle up.. then you move the sensor back to the middle by G0 Xnotedx Ynotedy ... so now you have Z 0 at the exact point below the sensor and then you move the sensor down till it triggers. This way you measure the real distance between the sensor and the nozzle.

OK, I agree that works as well.  Do you think many people use this process?  I think most rely on doing the offset at G28, where we already know where Z=0 is, because the probe (acting as an endstop) told us.  I don't think that the documentation which comes with SkyNet3D says to do it your way either.

**Comment by benlye** [comment]
> The Z offset is never different! You don't seem to understand how it works! The Z-Offset is (again) the distance between nozzle and sensor! It is constant everywhere besides of slight tilting of the head which gives slightly different results for the distance even on a flat bed if the x axis is tilt because the z-rods are not even. which is another thing that needs to be correct for everything to work.

Please re-read my example.  I'm not saying that the actual z-offset changes, just that it is possible to measure it differently if you are careless (and don't use the G92 Z0 process you describe above).

**Comment by oderwat** [comment]
Well you said exactly that:

> However, if your move your nozzle to another point on the bed, because the bed is not level or flat, when you drive the nozzle down to the bed your **Z-offset will be different**, because the bed can be nearer to or further away from the absolute Z-axis point where we hit the endstop

I guess you mean "the trigger point of the probe can be different". And yes. Thats why we have ABL in the first place. And when we compensate this difference and add the z-offset. we are at 0 again.

> imagine you measure -2.1 because this point in the bed is 0.1mm lower than the G28 point. If you set -2.1 as your Z-offset you are not going to have good luck printing

If you measure there, you also move the nozzle down at that point and select the z=0 at this point and then you will again have the same z-offset.

I **never** measure the offset regarding to G28 ... I move the nozzle down to the bed.. move it up until the sensor is off and then down till the sensor triggers. the z coordinate is the z offset. this has nothing to do with G28 at all!

> because the printer will expect an offset of -2.1 at the point where the Z-endstop occurs - i.e. at the G28 XY coordinates.

And you again write as if the "z-offset" would change..  the printer will expect the offset just everywhere! If you don't ABL it will just use the offset everywhere. If you ABL it will use this to tilt the bed but still use the offset everywhere.

You seem to miss that with this setup G28 is doing nothing at all but just moving your head to the middle. Measuring the Z offset is not dependent on what G28 "measures" at all.

OK, when we agree that the z offset is a constant ... it does not matter where you measure it. It is just constant everywhere.

On my printer X_MAX/2 and Y_MAX/2 is 110 110 .. which is the center and therefor the middle of all unbalanced points and exactly where the sensor measures for z = 0. Why should it even try to measure somewhere else than in the middle?

I don't see how your change does help compensating the problem that the sensor measure point is not the same as the nozzle position. Neither I can see how a point in an shifted coordinate system is better than to use the original coordinates. You just use the probe points which are cropped, such that you don't hit something because of the probe is not able to reach that point without hitting either min or max.

And about "what will people use to calibrate their sensor" ... well I don't to care to much. But currently I can tell peter what I think is cool to write into the skynet docs. I can tell it to about 1000 people in the fb group where I am active. And I may even write a Z-leveling procedure into the firmware, which optionally may even be able to do the whole process 100% automatically. 

Here the full procedure.. you may want to try that

; Heat up your bed and hotend to usual temperatures
M502 ; load firmware defaults
M851 Z0 ; reset z-offset
M500 ; store to EEPROM
G28 ; X Y and Z hominx. probe is in center of bed afterwards
M114 ; read and note x and y positions
G0 X110 Y110 ; move nozzle to the center
; lower nozzle till it hits the bed (paper gripping)
G92 Z0 ; define position as zero point for z
; move nozzle up until probe is off
G0 Xnoted Ynoted ; use values you made a note of above
M140 S0 ; switch of bed heater so it will not interfere electrically with the probe
; move the nozzle down really slow 0.1 / 0.05 mm per step until it triggers
M114 ; notice the z value reported. this negated is your z-offset
M851 Z-12.34 ; "12.34" stands for the z offset above before negating
M500 ; store it to the EEPROM
G28 ; X Y Z Home. Probe is back at the center of the bed
G30 ; the reported z for G30 has to be your z-offset +/- 0.0x

Try multiple G30 in that location. if it is off more than +/- 0.0x throw the probe away and get another one..

And remember: To get the optimum out of your auto-leveling you should level your bed manually from time :)

**Comment by benlye** [comment]
Your right, I confused my terminology, a lot.  I'm new to this and just trying to figure it out as much as I can.  Thanks for taking the time to explain it.

I really like your procedure for measuring the offset, and am trying it out now.  One thing I have noticed is that the probe on/off values are different to the G30 report.  If I do as you say I find that my probe triggers at 2.91mm when moved down and clears when I move up to 2.95mm, OK, I have a tolerance of about 0.04mm.  If I use G30 I consistently get a reported measurement of 2.83mm.  Somewhere in the middle is the ideal value, and I choose to set 2.85mm as the Z-offset.  I do all of this on the center of the bed, as you describe.

~~What I still find odd is that when I run G29, and the sensor probes the exact same spot I used for my measurements, I get a compensation value, when it seems to me that the value here should be 0.  I guess I'm still missing something.~~

Again, thanks for taking the time.  Sorry if I frustrated you.

**Comment by oderwat** [comment]
I am not sure where you see that compensation value. A lot of people misinterpret the rotation matrix identity diagonal entries. If you want to get a real representation about what the printer thinks your bed looks like you can use:

G29 P7 T V4

And feed the output table after the (0, 0) into this site: http://www.maui-3d.com/cgi-bin/plotG29

But you need to have "linear bed leveling" activated or need to compile bilinear with 7 points.

Output looks like this: 

image

Which shows two spots on my bed where my IR differential sensor does not trigger in the same range as the other spots (they are partial scratched and therefor reflect differently).

**Comment by benlye** [comment]
I use bilinear levelling.  I thought that this was he correction matrix, rather than the identity matrix you get for linear.  Am I wrong about that as well?

Bilinear Leveling Grid:
      0     1     2     3     4
 0 +0.03 +0.07 +0.10 +0.18 +0.27
 1 +0.02 +0.02 +0.01 +0.06 +0.11
 2 -0.03 -0.02 -0.06 -0.04 +0.00
 3 +0.00 +0.03 +0.01 +0.02 +0.04
 4 +0.01 +0.08 +0.09 +0.12 +0.20

**Comment by oderwat** [comment]
This shows the measured differences and uses (currently) an easy bilinear calculation for adjust Z (and only Z). So I think it shows what you think it does.

**Comment by benlye** [comment]
> I really like your procedure for measuring the offset, and am trying it out now. One thing I have noticed is that the probe on/off values are different to the G30 report. If I do as you say I find that my probe triggers at 2.91mm when moved down and clears when I move up to 2.95mm, OK, I have a tolerance of about 0.04mm. If I use G30 I consistently get a reported measurement of 2.83mm. Somewhere in the middle is the ideal value, and I choose to set 2.85mm as the Z-offset. I do all of this on the center of the bed, as you describe.

I figured out where I went wrong, and I'm pretty sure I know why I see the discrepancy in values and why my correction matrix is over-correcting - I missed at least two important steps which led me to falsely set my offset, because I was starting from the false point.

> ; Heat up your bed and hotend to usual temperatures
M502 ; load firmware defaults
M851 Z0 ; reset z-offset
M500 ; store to EEPROM
G28 ; X Y and Z hominx. probe is in center of bed afterwards
M114 ; read and note x and y positions
G0 X110 Y110 ; move nozzle to the center
; lower nozzle till it hits the bed (paper gripping)
G92 Z0 ; define position as zero point for z
; move nozzle up until probe is off
G0 Xnoted Ynoted ; use values you made a note of above
M140 S0 ; switch of bed heater so it will not interfere electrically with the probe
; move the nozzle down really slow 0.1 / 0.05 mm per step until it triggers
M114 ; notice the z value reported. this negated is your z-offset
M851 Z-12.34 ; "12.34" stands for the z offset above before negating
M500 ; store it to the EEPROM
G28 ; X Y Z Home. Probe is back at the center of the bed
G30 ; the reported z for G30 has to be your z-offset +/- 0.0x

I think you should ask Peter to make this the default z-offset setting guide in the doc.  It takes a little longer but there is no ambiguity.  It may help avoid future newbie problems / misunderstandings.

Thanks again for taking the time and putting me on the right path.

**Pull request closed without merging**
